name: deep-learning-cpu
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2022.2.1
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - cpuonly=2.0
  - cryptography=36.0.0
  - cycler=0.11.0
  - fonttools=4.30.0
  - freeglut=3.2.2
  - freetype=2.10.4
  - icu=68.2
  - idna=3.3
  - intel-openmp=2021.4.0
  - jasper=2.0.33
  - jpeg=9d
  - kiwisolver=1.4.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=11.1.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libopencv=4.5.2
  - libpng=1.6.37
  - libprotobuf=3.15.8
  - libtiff=4.2.0
  - libuv=1.40.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - lz4-c=1.9.3  
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2  
  - munkres=1.1.4
  - numpy=1.21.5  
  - opencv=4.5.2
  - openssl=1.1.1m
  - packaging=21.3
  - pillow=9.0.1
  - pip=21.2.4
  - py-opencv=4.5.2
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytorch=1.11.0
  - pytorch-mutex=1.0
  - qt=5.12.9
  - requests=2.27.1
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.38.0
  - tk=8.6.11
  - torchaudio=0.11.0
  - torchvision=0.12.0
  - tornado=6.1
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - unicodedata2=14.0.0
  - urllib3=1.26.8    
  - wheel=0.37.1    
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - albumentations==1.1.0
    - colorama==0.4.4
    - imageio==2.16.1
    - joblib==1.1.0
    - networkx==2.7.1
    - opencv-python-headless==4.5.5.64
    - pywavelets==1.3.0
    - pyyaml==6.0
    - qudida==0.0.4
    - scikit-image==0.19.2
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - threadpoolctl==3.1.0
    - tifffile==2022.3.16
    - tqdm==4.63.0
